# Generated by Django 5.1.6 on 2025-03-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_org_admin',
            field=models.BooleanField(default=False),
        ),
    ]
